# Use root/example as user/password credentials
version: '3.8'

services:

  mysql:
    image: mysql/mysql-server:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: spring
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: ies
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - ~/docker/mysql:/var/lib/mysql

  mongodb:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ~/docker/mongodb:/data/db